version: "3.2"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    #restart: always
    volumes:
      - ./app:/app
    #ports:
    #  - "3000:3000"
    #depends_on:
    #  - postgresql
    dns: 8.8.8.8